deenxl/urls.py
from django.contrib import admin
from django.urls import path, include
from questions.views import index_view

urlpatterns = [
    path('', index_view, name='index'),
    path('questions/', include('questions.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),

]

questions/urls.py
from django.urls import path

from . import views
from .views import choiceCreateView

app_name = 'questions'
urlpatterns = [
    path('ajax/load-choices/', views.load_choices, name='ajax_load_choices'),

    path('create/', views.QuestionCreateView.as_view(), name='question-create'),
    path('update/<int:pk>/', views.QuestionUpdateView.as_view(), name='question-update'),
    path('list/', views.QuestionListView.as_view(), name='question-list'),
    path('list/all/', views.QuestionListAllView.as_view(), name='question-list-all'),  #see everyone's questions
    path('detail/<int:pk>/', views.QuestionDetail, name='question-detail'),
    # path('delete/<int:pk>/', views.DeleteView.as_view(), name='question-delete'),

    path('admin-update/<int:pk>/', views.QuestionAdminUpdateView.as_view(), name='question-admin-update'),

    path('choice/group/create/', views.ChoiceGroupCreateView.as_view(), name='choice-group-create'),
    path('choice/group/update/<int:pk>/', views.ChoiceGroupUpdateView.as_view(), name='choice-group-update'),
    # path('choice/group/list/', views.ChoiceGroupListView.as_view(), name='choice-group-list'),
    # path('choice/group/detail/<int:pk>/', views.ChoiceGroupDetailView.as_view(), name='choice-group-detail'),
    # path('choice/group/delete/<int:pk>/', views.ChoiceGroupDeleteView.as_view(), name='choice-group-delete'),

    path('choice/create/<int:pk>/', choiceCreateView, name='choice-create'),
    # path('choice/update/<int:pk>/', views.ChoiceUpdateView.as_view(), name='choice-update'),
    # path('choice/list/', views.ChoiceListView.as_view(), name='choice-list'),
    # path('choice/detail/<int:pk>/', views.ChoiceDetailView.as_view(), name='choice-detail'),
    # path('choice/delete/<int:pk>/', views.ChoiceDeleteView.as_view(), name='choice-delete'),

    path('copy/<int:pk>/', views.QuestionCopy, name='question-copy'),
    path('generate/<int:pk>/', views.QuestionGenerate, name='question-generate'),
    path('answer/check/<int:pk>/', views.questionCheckAnswer, name='question-answer-check'),

    # path('choice/download/', views.choiceDownload, name='choice-download'),
    # path('choice/group/download/', views.choiceGroupDownload, name='choice-group-download'),
    # path('question/download/', views.questionDownload, name='question-download'),
    # path('answer/display/', views.questionAnswerDisplay, name='question-answer-display'),
    # path('choice/upload/', views.choiceUpload, name='choice-upload'),
]

questions/models.py
from django.conf import settings
from django.db import models
# from django.contrib import admin
from django.urls import reverse
# from django.utils.translation import gettext_lazy as _

# Create your models here.

class ChoiceGroup(models.Model):
    choice_group = models.CharField(max_length=100, unique=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.SET_NULL,
                                   editable=False)
    created = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-last_modified']

    def get_absolute_url(self):
        return reverse('questions:choice-group-create', kwargs={'pk': self.pk})

    def __str__(self):
        return self.choice_group


class Choice(models.Model):
    choice = models.CharField(max_length=1000)
    choice_group = models.ForeignKey('ChoiceGroup', on_delete=models.PROTECT)
    # created_by = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.SET_NULL,
    #                                editable=False)
    created = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['last_modified']
        unique_together = [['choice', 'choice_group']]

    def __str__(self):
        return self.choice


class Subject(models.Model):
    subject = models.CharField(max_length=100)

    class Meta:
        ordering = ['subject']

    def __str__(self):
        return self.subject


class Level(models.Model):
    level = models.CharField(max_length=2)
    display_order = models.IntegerField(default=0)

    class Meta:
        ordering = ['display_order']

    def __str__(self):
        return self.level


class Question(models.Model):
    question_text = models.TextField(verbose_name='Question')
    choice_group = models.ForeignKey('ChoiceGroup', on_delete=models.PROTECT, verbose_name='Choice Group')
    choice = models.ForeignKey('Choice', on_delete=models.PROTECT, verbose_name='Correct Answer')
    notes = models.TextField(null=True, blank=True)
    feedback = models.TextField(null=True, blank=True)
    subject = models.ManyToManyField(Subject)
    level = models.ManyToManyField(Level)

    UNREVIEWED = 'UNREVIEWED'
    PENDING = 'PENDING'
    REJECTED = 'REJECTED'
    ACCEPTED = 'ACCEPTED'
    FINALIZED = 'FINALIZED'
    REVIEW_STATUS_CHOICES = [
        (UNREVIEWED, 'UNREVIEWED'),
        (PENDING, 'PENDING'),
        (REJECTED, 'REJECTED'),
        (ACCEPTED, 'ACCEPTED'),
        (FINALIZED, 'FINALIZED'),
    ]

    review_status = models.CharField(max_length=100, null=True, blank=True, verbose_name='Review Status', choices=REVIEW_STATUS_CHOICES, default=UNREVIEWED)

    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.SET_NULL,
                                   editable=False)
    created = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)

    # class Meta:
    # verbose_name_plural = "questions_standard"
    class Meta:
        ordering = ['-last_modified']
        # works, but not needed at this time
        # permissions = (
        #         ('can_edit_unreviewed_questions', 'Can Edit Unreviewed Questions'),
        # )

    def __str__(self):
        return self.question_text

questions/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.template import loader
from django.urls import reverse
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, UpdateView, ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
# from guardian.mixins import PermissionRequiredMixin
# from guardian.shortcuts import get_objects_for_user
from random import randint, shuffle
from django.contrib import messages
from django.http import HttpResponse
from tablib import Dataset

from .models import Question, Choice, ChoiceGroup, Subject
from .forms import QuestionForm, ChoiceForm, QuestionAdminForm
from .resources import *
from django.forms import inlineformset_factory


# Delete Questions, then Choices, then Groups
def index_view(request):
    return render(request, 'questions/index.html')


class QuestionCreateView(LoginRequiredMixin, CreateView):
    model = Question
    form_class = QuestionForm
    # fields = '__all__'
    success_url = reverse_lazy('questions:question-list')


    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class QuestionUpdateView(UserPassesTestMixin, UpdateView):
    model = Question
    form_class = QuestionForm

    # fields = ('question_text', 'choice_group', 'choice', 'notes',)
    success_url = reverse_lazy('questions:question-list')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def test_func(self):
        if (self.request.user == self.get_object().created_by):
            return True
        else:
            return False


class QuestionAdminUpdateView(UserPassesTestMixin, UpdateView):
    model = Question
    form_class = QuestionAdminForm

    # fields = ('question_text', 'choice_group', 'choice', 'notes',)
    success_url = reverse_lazy('questions:question-list-all')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def test_func(self):
        if self.request.user.username == 'admin':  #Admin user id
            return True
        else:
            return False




class QuestionListView(LoginRequiredMixin, ListView):
    model = Question

    def get_queryset(self):
        user = self.request.user
        question_list = Question.objects.order_by("-last_modified").filter(created_by=user).filter(review_status='UNREVIEWED')
        return question_list

class QuestionListAllView(LoginRequiredMixin, ListView):
    model = Question
    template_name = "questions/question_list_all.html"
    # permission_required = ('questions.can_view_all_questions')

    def get_queryset(self):
        # user = self.request.user
        question_list = Question.objects.order_by("-last_modified").filter(review_status='UNREVIEWED')
        return question_list

# class QuestionDetailView(DetailView):
#     model = Question
#     # template_name = "questions/permission_required.html"
#     # permission_required = ('questions.can_view_all_questions')
#
#     def get_queryset(self):
#         # user = self.request.user
#         question_list = Question.objects.order_by("-last_modified").filter(review_status='UR')
#         return question_list
#
#     def get_context_data(self, **kwargs):
#         context = super(QuestionDetailView, self).get_context_data(**kwargs)
#         context['choices'] = Choice.objects.filter(self.model.choice_group)
#         # other code
#         return context

# class QuestionDetailView(LoginRequiredMixin, DetailView):
#     model = Question


# class QuestionDeleteView(LoginRequiredMixin, DeleteView):
#     model = Question
#     success_url = reverse_lazy('questions:question-list')
#
#     def get_queryset(self):
#         user = self.request.user
#         question_list = Question.objects.filter(created_by=user)
#         return question_list

def load_choices(request):
    choice_group_id = request.GET.get('choice_group')
    choices = Choice.objects.filter(choice_group_id=choice_group_id)
    return render(request, 'questions/choice_dropdown_list_options.html', {'choices': choices})


class ChoiceGroupCreateView(LoginRequiredMixin, CreateView):
    model = ChoiceGroup
    # form_class = ChoiceGroupForm
    fields = '__all__'
    # success_url = 'questions:index'
    success_url = reverse_lazy('questions:choice-group-create')

    # form = QuestionForm

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.username == "admin":
            context["objects"] = self.model.objects.all().order_by('last_modified')
        else:
            context["objects"] = self.model.objects.order_by('last_modified').filter(created_by=self.request.user)
        return context


class ChoiceGroupUpdateView(LoginRequiredMixin, UpdateView):
    model = ChoiceGroup
    fields = ('choice_group',)
    success_url = reverse_lazy('questions:choice-group-create')


# Works but don't need it
# class ChoiceGroupListView(LoginRequiredMixin, ListView):
#     model = ChoiceGroup
#     # permission_required = ('kidsapp.view_denial')
#     def get_queryset(self):
#         user = self.request.user
#         choice_group_list = ChoiceGroup.objects.filter(created_by=user)
#         return choice_group_list


# class ChoiceGroupDetailView(LoginRequiredMixin, DetailView):
#     model = ChoiceGroup


# class ChoiceGroupDeleteView(LoginRequiredMixin, DeleteView):
#     model = ChoiceGroup
#     success_url = reverse_lazy('author-list')
#
#     def get_queryset(self):
#         user = self.request.user
#         choice_group_list = ChoiceGroup.objects.filter(created_by=user)
#         return choice_group_list


# class ChoiceCreateView(LoginRequiredMixin, CreateView):
#     model = Choice
#     # form_class = ChoiceGroupForm
#     fields = '__all__'
#     # success_url = 'questions:index'
#     success_url = reverse_lazy('questions:choice-list')
#
#     # form = QuestionForm
#
#     def form_valid(self, form):
#         form.instance.created_by = self.request.user
#         return super().form_valid(form)

def choiceCreateView(request, pk):
    # form = ChoiceForm
    ChoiceFormSet = inlineformset_factory(ChoiceGroup, Choice, form=ChoiceForm, fields=('choice',), extra=5)
    choice_group = ChoiceGroup.objects.get(id=pk)

    if request.method == 'POST':
        formset = ChoiceFormSet(request.POST, instance=choice_group)
        if formset.is_valid():
            formset.save()
            return redirect('questions:choice-create', pk=choice_group.id)

    # IMPORTANT: Change queryset objects.none() to not show older items in list
    # formset = ChoiceFormSet(queryset=Choice.objects.none(),instance=choice_group)
    formset = ChoiceFormSet(queryset=Choice.objects.all(), instance=choice_group)
    context = {'formset': formset, 'choice_group': choice_group}
    return render(request, 'questions/choice_form.html', context)


class ChoiceUpdateView(LoginRequiredMixin, UpdateView):
    model = Choice
    fields = ('choice',)
    success_url = reverse_lazy('questions:choice-list')

    # def get_queryset(self):
    #     user = self.request.user
    #     choice_list = Choice.objects.filter(created_by=user)
    #     return choice_list


class ChoiceListView(LoginRequiredMixin, ListView):
    model = Choice


# class ChoiceDetailView(LoginRequiredMixin, DetailView):
#     model = Choice


# class ChoiceDeleteView(LoginRequiredMixin, DeleteView):
#     model = Choice
#     success_url = reverse_lazy('questions:choice-list')

def QuestionCopy(request, pk):
    # form_class = QuestionForm

    question = Question.objects.get(id=pk)
    question.pk = None
    # question.question_text = 'COPY:' + question.question_text
    question.save()
    # new_id = question.id
    # context = {'question':question}

    # if request.method == 'POST':
    #     formset = ChoiceFormSet(request.POST, instance = choice_group)
    #     if formset.is_valid():
    #         formset.save()
    #         return redirect('questions:choice-create', pk = choice_group.id)

    return redirect('questions:question-update', pk=question.id)
    # return render(request, "questions/question_copy.html", context)
    # questions / question_form.html


def QuestionDetail(request, pk):
    question = Question.objects.get(id=pk)
    choice_group = question.choice_group
    correct_choice = question.choice
    # Below is needed to create a Queryset for combining
    correct_choice_qs = Choice.objects.filter(choice_group=choice_group, choice=correct_choice).order_by("?")[:1]
    wrong_choices = Choice.objects.filter(choice_group=choice_group).exclude(choice=correct_choice)
    all_choices = correct_choice_qs | wrong_choices

    all_choices_list = list(all_choices)
    # shuffle(all_choices_list)

    context = {'question': question, 'all_choices': all_choices_list}
    return render(request, "questions/question_detail.html", context)



def QuestionGenerate(request, pk):
    question = Question.objects.get(id=pk)
    choice_group = question.choice_group
    correct_choice = question.choice
    # Below is needed to create a Queryset for combining
    correct_choice_qs = Choice.objects.filter(choice_group=choice_group, choice=correct_choice).order_by("?")[:1]
    wrong_choices = Choice.objects.filter(choice_group=choice_group).exclude(choice=correct_choice).order_by("?")[:4]
    all_choices = correct_choice_qs | wrong_choices

    all_choices_list = list(all_choices)
    shuffle(all_choices_list)

questions/templates/questions/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.png' %}"/>
    <title>{% block title %}{% endblock %} - Islamic Education</title>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->

{#  <link rel="stylesheet" href="{% static 'css/styles.css' %}">#}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha256-pasqAKBDmFT4eHoN2ndd6lN370kFiGUFyTiUHWhU7k8="
        crossorigin="anonymous">
    </script>

    <link rel="stylesheet"  type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">

    <script
        src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js">
    </script>

</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
          <div class="p-3 mb-2 bg-light text-dark">
        <ul class="sidebar-nav">
            {% if user.is_authenticated %}
                <li>User: {{ user.get_username }}</li>
                <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
                <li><a href="{% url 'password_change' %}">Change password</a></li>

            {% else %}
                 <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
            {% endif %}
        </ul>
        <br>

        <ul>
            <li><a href="{% url 'index' %}">Home</a></li>
            <li><a href="{% url 'questions:choice-group-create' %}">Choice Groups</a></li>
            <li><a href="{% url 'questions:question-create' %}">Create Question</a></li>
            <li><a href="{% url 'questions:question-list'  %}">My Questions</a></li>
            <li><a href="{% url 'questions:question-list-all'  %}">Everyone's Questions</a></li>

        </ul>


        <ul>
            <li><a href="/admin">Admin</a> </li>
        </ul>
     </div>
     {% endblock %}
      </div>
      <div class="col-sm-10 " >
            <div class="p-3 mb-2 bg-light text-dark">
                {% block content %}

                {% endblock %}
            </div>
      </div>
    </div>
  </div>
</body>
</html>

questions/templates/questions/choice_dropdown_list_options.html
<option value="">---------</option>
{% for choice in choices %}
<option value="{{ choice.pk }}">{{ choice.choice }}</option>
{% endfor %}

questions/templates/questions/choice_form.html
{% extends "questions/base.html" %}

{% block title %}Choice Edit{% endblock %}

{% block content %}


<form method="post">
    {% csrf_token %}
<h3>{{ choice_group.choice_group }}</h3>
    {{ formset.management_form }}

{{ formset.forms.reverse }}
<br>
        {% for form in formset %}
            {{ form }}
            <hr>
        {% endfor %}





    <input type="submit" value="Submit">

</form>

{% endblock %}

questions/templates/questions/choicegroup_form.html
{% extends "questions/base.html" %}

{% block title %}Choice Group Edit{% endblock %}

{% block content %}

    <br>
<form method="post">
    {% csrf_token %}
    {{ form }}

    <input type="submit" value="Submit">
</form>
<br>

{#    <table class="table table-bordered table-sm ">#}
        <table id="myTable" class="hover compact cell-border" data-page-length='100' style="width:100%">
        <thead>
        <tr>
            <td>Choice Group</td>
            <td>Action</td>
            <td>Created by</td>
            <td>Modified</td>
        </tr>
        </thead>
            {% for cg in objects %}
            <tr>
                <td><a href="{% url 'questions:choice-create' cg.pk %}">{{ cg.choice_group }}</a></td>
                <td><button class="btn btn-outline-secondary btn-sm"><a href="{% url 'questions:choice-group-update' cg.pk %}">Rename</a></button></td>
                <td>{{ cg.created_by }}</td>
                <td>{{ cg.last_modified }}</td>
            </tr>
        {% endfor %}
    </table>

       <script>
        $(document).ready( function () {
            {#$('#myTable').DataTable();#}

            $('#myTable').DataTable({
                "order": [3, "desc"]  //sort order 0 based columns
                {#"order": [[0, "desc"], [1, "asc"]]  //sort order 0 based columns#}
            });
        })
    </script>

{% endblock %}

questions/templates/questions/index.html
{% extends "questions/base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
    <br><br>
    <h3>Islamic Studies</h3>
    <p>Five steps to making questions:</p>
    <ol>
    <li>Create a Choice Group</li>
    <li>Add Choices to the Group</li>
    <li>Create Question</li>
    <li>Generate Question Previews</li>
    <li>Use Copy function to Create Similar Questions</li>
    </ol>
{% endblock %}

questions/templates/questions/old_choicegroup_detail.html
{% extends "questions/base.html" %}

{% block title %}Choice Group Details{% endblock %}

{% block content %}

<body>

{{ object.choice_group }}

</body>


{% endblock %}

questions/templates/questions/old_choicegroup_list.html
{% extends "questions/base.html" %}

{% block title %}Choice Group List{% endblock %}

{% block content %}

<body>

    <table>
    {% for cg in object_list %}
        <tr>
{#            <td>{{ cg.choice_group }}</td>#}
            <td><button><a href="{% url 'questions:choice-create' cg.pk %}">Edit</a></button></td>
            <td><a href="{% url 'questions:choice-group-update' cg.pk %}">{{ cg.choice_group }}</a></td>

        </tr>
    {% empty %}
        <tr><td>No Choice Groups yet.</td></tr>
    {% endfor %}
    </table>

</body>


{% endblock %}

questions/templates/questions/question_answer.html
{% extends "questions/base.html" %}

{% block title %}Question Answer{% endblock %}

{% block content %}

<body>
<h3>Teacher Solution Display</h3>
<br>
{#<form method="post" action="{% url 'questions:question-answer' question.pk %}">#}
{#{% csrf_token %}#}
   <h5> {{ question.question_text }}</h5>
You answered: {{ given_answer }}
<br>
Correct answer: {{ correct_answer }}
<br>
<br>
Your answer is:
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

    <button class="btn btn-outline-primary btn-sm"><a href="{% url 'questions:question-list' %}">Back to Question List</a></button>
</body>


{% endblock %}

questions/templates/questions/question_detail.html
{% extends "questions/base.html" %}

{% block title %}Question Generated{% endblock %}

{% block content %}


<h3>Question Details</h3>
<br>
   <h5> {{ question.question_text }}</h5>
    <ul>
    {% for choice in all_choices %}
        <li>{{ choice.choice }}</li>
    {% endfor %}
    </ul>

    <h6>Correct Answer: {{ question.choice }}</h6>
    <p>Written by: <b>{{ question.created_by }}</b></p>

    {% if user.username == 'admin' %}
        <button class="btn btn-outline-primary btn-sm"><a href="{% url 'questions:question-admin-update' question.pk %}">Edit</a></button>
    {% endif %}

{% endblock %}

questions/templates/questions/question_feedback.html
{% extends "questions/base.html" %}

{% block title %}Question Feedback{% endblock %}

{% block content %}

<h3>Teacher Solution Display</h3>
<br>
{#<form method="post" action="{% url 'questions:question-answer' question.pk %}">#}
{#{% csrf_token %}#}
   <h5> {{ question.question_text }}</h5>
<ul>
<li>You answered: <b>{{ given_answer }}</b></li>
<li>Correct answer: <b>{{ correct_answer }}</b></li>
</ul>
Your answer is:
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}><b>{{ message }}</b></li>
    {% endfor %}
</ul>
{% endif %}

    <button class="btn btn-outline-primary btn-sm"><a href="{% url 'questions:question-list' %}">Back to Question List</a></button>



{% endblock %}

questions/templates/questions/question_form.html
{% extends "questions/base.html" %}

{% block title %}Create Question{% endblock %}

{% block content %}


<br>
<form method="post" id="questionForm" data-choices-url="{% url 'questions:ajax_load_choices' %}">
    {% csrf_token %}
    <table >
        {{ form }}
    </table>
    <br>
    <input type="submit" value="Submit">
    <input type="reset" >

</form>


 <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    $("#id_choice_group").change(function () {
      var url = $("#questionForm").attr("data-choices-url");  // get the url of the `load_cities` view
      var choice_group_Id = $(this).val();  // get the selected country ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'choice_group': choice_group_Id       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_choice").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });

    });
  </script>


{% endblock %}

questions/templates/questions/question_generate.html
{% extends "questions/base.html" %}

{% block title %}Question Generated{% endblock %}

{% block content %}


<h3>Teacher Question Display</h3>
<br>
<form method="post" action="{% url 'questions:question-answer-check' question.pk %}">
{% csrf_token %}
   <h5> {{ question.question_text }}</h5>

    {% for choice in all_choices %}
        <label><input type="radio" required name="displayed_choices" id="id_{{ choice.choice }}" value="{{ choice.choice }}">{{ choice.choice }}</label>
        <br>
    {% endfor %}

{#    <input type="submit" value="Submit>#}
    <button type="submit">Submit</button>

</form>
<br>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<br>
    <h6>Correct Answer: {{ question.choice }}</h6>

    <button class="btn btn-outline-primary btn-sm"><a href="{% url 'questions:question-generate' question.pk %}">Generate Another Version</a></button>


{% endblock %}

questions/templates/questions/question_list.html
{% extends "questions/base.html" %}

{% block title %}Question List{% endblock %}

{% block content %}


    <table id="myTable" class="hover compact cell-border" data-page-length='10' style="width:100%">
{#    <table class="table table-bordered table-sm ">#}
    <thead>
        <tr>
            <td>Question</td>
            <td>Correct Choice</td>
            <td>Choice Group</td>
            <td>Action</td>
            <td>Modified</td>
        </tr>
    </thead>
    <tbody>
    {% for question in object_list %}
        <tr>
            <td><a href="{% url 'questions:question-update' question.pk %}">{{ question.question_text }}</a></td>
            <td>{{ question.choice }}</td>
            <td>{{ question.choice_group }}</td>
            <td>
                <button class="btn btn-outline-secondary btn-sm"><a href="{% url 'questions:question-copy' question.pk %}">Copy</a></button>
                <button class="btn btn-outline-primary btn-sm"><a href="{% url 'questions:question-generate' question.pk %}">Generate</a></button>
            </td>
            <td>
                {{ question.last_modified }}
            </td>

        </tr>
    {% endfor %}
    </tbody>
    </table>

    <script>
        $(document).ready( function () {
            {#$('#myTable').DataTable();#}

            $('#myTable').DataTable({
                "order": [4, "desc"]  //sort order 0 based columns
                {#"order": [[0, "desc"], [1, "asc"]]  //sort order 0 based columns#}
            });
        })
    </script>



{% endblock %}

questions/templates/questions/question_list_all.html
{% extends "questions/base.html" %}

{% block title %}Everyone's Questions List{% endblock %}

{% block content %}


    <table id="myTable" class="hover compact cell-border" data-page-length='100' style="width:100%">
{#    <table class="table table-bordered table-sm ">#}
    <thead>
        <tr>
            {% if user.username == 'admin' %}
                <td>Action</td>
            {% endif %}
            <td>Question</td>
            <td>Correct Choice</td>
            <td>Choice Group</td>
            <td>Created By</td>
            <td>Modified</td>
        </tr>
    </thead>
    <tbody>
    {% for question in object_list %}
        <tr>
            {% if user.username == 'admin' %}
                <td><button class="btn btn-outline-primary btn-sm"><a href="{% url 'questions:question-admin-update' question.pk %}">Edit</a></button></td>
            {% endif %}
            <td><a href="{% url 'questions:question-detail' question.pk %}">{{ question.question_text }}</a></td>
            <td>{{ question.choice }}</td>
            <td>{{ question.choice_group }}</td>
            <td>{{ question.created_by }}</td>
            <td>{{ question.last_modified }}</td>

        </tr>
    {% endfor %}
    </tbody>
    </table>

    <script>
        $(document).ready( function () {
            {#$('#myTable').DataTable();#}

            $('#myTable').DataTable({
                "order": [5, "desc"]  //sort order 0 based columns
                {#"order": [[0, "desc"], [1, "asc"]]  //sort order 0 based columns#}
            });
        })
    </script>



{% endblock %}